# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eIJCgKKpQIzdLQKXLHtWS84wLIEXuvIb
"""

import streamlit as st
import librosa
import pyworld as pw
import numpy as np
import pysptk
import soundfile as sf
import io
import matplotlib.pyplot as plt

# ================================================
# ロジック部分 (run_full_analysis, HarmoSynthesizer)
# ================================================

def run_full_analysis(x, fs, penta=0.5, precise_f0=False, key_original=True, W_triad=0.2, W_vi=0.5):
    """
    音声波形 x を受け取り、WORLD分析とキー判定を実行する。
    """
    # --- 1. WORLD分析 ---
    try:
        x = x.astype(np.float64) # PyWorld用にfloat64に変換
        if precise_f0:
            f0, t = pw.harvest(x, fs)
        else:
            f0, t = pw.dio(x, fs)
            f0 = pw.stonemask(x, f0, t, fs)

        sp = pw.cheaptrick(x, f0, t, fs)
        ap = pw.d4c(x, f0, t, fs)
        f0 = f0 * (ap[:,0] < 0.5) # 無音区間フィルタリング

    except Exception as e:
        st.error(f"分析エラー: {e}")
        return None, None, None, None, None, None

    # --- 2. キー分析プロファイルの定義 ---
    # KS法プロファイル (Cマイナー風 - 元コード準拠)
    C_ks = np.array([1, 0, penta, 1, 0, 1, 0, 1, penta, 0, 1, 0])
    key_mat_KS = np.stack([np.roll(C_ks, i) for i in range(12)])

    # トニック・トライアド(主和音)プロファイル
    C_triad = np.array([1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0])
    matrix_Triad = np.stack([np.roll(C_triad, i) for i in range(12)])

    # 音名(N)の計算
    f0_for_calc = f0.copy()
    f0_for_calc[f0 == 0] = 1e-10
    N = ((np.log2(f0_for_calc) - np.log2(440) + 1/24)*12//1%12).astype(np.int8)

    # --- 3. スコア計算 (ヒストグラム) ---
    v = np.array([])
    f0_voiced = f0[f0 != 0]
    if len(f0_voiced) == 0:
        return None, None, None, None, None, None

    if key_original:
        normed_f0 = (np.log2(f0_voiced) - np.log2(440) + 1/24) % 1
        v = np.histogram(normed_f0, bins=12, range=(0, 1))[0]
    else:
        def f02tone(f0):
            return (np.log2(f0+1e-10) - np.log2(440) + 1/24)*12//1
        def longtone_hist(f0):
            N = f02tone(f0)
            x_ = f0[1:] * ((N[1:] -  N[:-1]) != 0.)* (ap[1:,0] < 0.5)
            tone = (f02tone(x_[x_!=0]))%12
            return np.histogram(tone,bins=12,range=(0,11))[0]
        v = longtone_hist(f0)
        
    # 「袋詰め」スコアを計算
    scores_KS = key_mat_KS @ v
    scores_Triad = matrix_Triad @ v
    final_scores = scores_KS + (W_triad * scores_Triad)

    # --- 4. スコア計算 (V-Iモーション) ---
    vi_scores = np.zeros(12)
    note_changes_idx = np.where(N[1:] != N[:-1])[0] + 1

    for idx in note_changes_idx:
        N_prev = N[idx - 1]
        N_curr = N[idx]

        if f0[idx-1] == 0 or f0[idx] == 0:
            continue

        for key_idx in range(12):
            tonic_note = key_idx
            dominant_note = (key_idx + 7) % 12

            if N_prev == dominant_note and N_curr == tonic_note:
                vi_scores[key_idx] += 1

    # 最終スコアに、V-Iスコアを重み付けして加算
    final_scores = final_scores + (W_vi * vi_scores)

    # --- 5. 結果の返却 ---
    best_index = np.argmax(final_scores)

    return x, f0, sp, ap, best_index, N, final_scores


class HarmoSynthesizer:
    def __init__(self, sr=48000, shift_up=True, warp_coeff=0.0, num_coeff=64, window_len=5,smooth_FM = False):
        self.sr = sr
        self.frame_period = 5
        self.fftlen = pw.get_cheaptrick_fft_size(self.sr)
        self.num_coeff = num_coeff

        if shift_up:
            self.pitch_shift = 2 ** (np.array([3,4,3,4,3,3,4,3,4,3,4,3])/12)
        else:
            self.pitch_shift = 2 **(-np.array([4,3,4,3,4,3,3,4,3,4,3,3])/12)

        self.warp_in = pysptk.util.mcepalpha(self.sr)
        self.warp_out = self.warp_in + warp_coeff
        self.use_warp = (self.warp_in != self.warp_out)

        if window_len > 1:
            window = np.hanning(window_len)
            self.window = window / np.sum(window)
        else:
            self.window = None
        self.smooth_FM = smooth_FM

    def pitch_coeff(self, f0, N, idx):
        v_ = np.roll(self.pitch_shift, -idx)
        f0_shifted = f0 * v_[N]
        if self.window is not None:
            if self.smooth_FM:
                f0_shifted = f0 * np.convolve(v_[N], self.window, 'same')
            else:
                f0_shifted = np.convolve(f0, self.window, 'same')
        return f0_shifted

    def freq_warp(self, sp):
        mc = pysptk.sp2mc(sp, self.num_coeff, self.warp_in)
        return pysptk.mc2sp(mc, self.warp_out, self.fftlen)

    def synth(self, f0, sp, ap, N, key_index):
        f0_ = self.pitch_coeff(f0, N, key_index)

        if self.use_warp:
            sp_ = self.freq_warp(sp)
        else:
            sp_ = sp

        # ノイズ対策: apのワープは行わず、元のapを使用
        ap_ = ap

        y = pw.synthesize(f0_, sp_, ap_, self.sr, self.frame_period)
        return y

# ================================================
# Streamlit UI 部分
# ================================================

st.title("🎵 自動ハモリ生成アプリ")
st.write("ボーカル音源(wav)をアップロードすると、キーを推定してハモリパートを生成します。")

# サイドバー設定
st.sidebar.header("設定")
key_original = st.sidebar.checkbox("固定長分割", value=True)
smooth_FM = st.sidebar.checkbox("シフト平滑化(またはピッチ平滑化)", value=False)
precise_f0 = st.sidebar.checkbox("正確なf0", value=False)
# 上ハモリ or 下ハモリ
harmo_mode = st.sidebar.radio(
    "ハモリの種類",
    ("上ハモリ (3度上)", "下ハモリ (3度下)"),
    horizontal=False
)

shift_up = (harmo_mode == "上ハモリ (3度上)")

penta_weight = st.sidebar.slider("ペンタトニック重み (PENTA)", 0.0, 1.0, 0.5)
amp = st.sidebar.slider("ハモリ音量 (AMP)", 0.0, 1.0, 0.5)

st.sidebar.subheader("詳細設定")
w_triad = st.sidebar.slider("トライアド重み (W_TRIAD)", 0.0, 1.0, 0.2)
w_vi = st.sidebar.slider("V-I進行重み (W_VI)", 0.0, 1.0, 0.5)
warp_coeff = st.sidebar.slider("声質変換 (WARP)", -0.2, 0.2, 0.0)

uploaded_file = st.file_uploader("WAVファイルをアップロード", type=["wav"])

if uploaded_file is not None:
    st.audio(uploaded_file, format='audio/wav')

    if st.button("ハモリ生成開始"):
        with st.spinner("分析・生成中... (数秒〜数十秒かかります)"):
            # 1. ファイル読み込み
            # Streamlitのアップロードファイルは直接librosaで読めるが、srを指定する
            x, sr = librosa.load(uploaded_file, sr=48000, dtype=np.float64)

            # 2. 分析実行
            x, f0, sp, ap, detected_key, N, scores = run_full_analysis(
                x, sr,
                penta=penta_weight,
                precise_f0=precise_f0, # 高速化のためDio固定
                key_original=key_original,
                W_triad=w_triad,
                W_vi=w_vi
            )

            if detected_key is not None:
                key_names_en = ["C", "Db", "D", "Eb", "E", "F", "F#", "G", "Ab", "A", "Bb", "B"]
                key_name = key_names_en[detected_key]
                st.success(f"推定されたキー: **{key_name}**")

                # スコアグラフの表示
                fig, ax = plt.subplots(figsize=(10, 4))
                ax.bar(key_names_en, scores, color='blue')
                ax.bar(key_names_en[detected_key], scores[detected_key], color='red')
                ax.set_title("Key Estimation Scores")
                st.pyplot(fig)

                # 3. ハモリ合成
                harmo = HarmoSynthesizer(
                    sr=sr,
                    shift_up=shift_up,
                    warp_coeff=warp_coeff,
                    smooth_FM = smooth_FM
                )
                y_hamori = harmo.synth(f0, sp, ap, N, detected_key)

                # 4. ミックス
                len_min = min(len(x), len(y_hamori))
                y_mixed = x[:len_min] + amp * y_hamori[:len_min]

                # 正規化
                max_val = np.max(np.abs(y_mixed))
                if max_val > 1.0:
                    y_mixed = y_mixed / max_val

                # 5. 結果表示
                st.subheader("生成結果")

                # WAVファイルとして書き出し (メモリ上)
                buffer = io.BytesIO()
                sf.write(buffer, y_mixed, sr, format='WAV')
                buffer.seek(0)

                st.audio(buffer, format='audio/wav')

                st.download_button(
                    label="ハモリ付き音源をダウンロード",
                    data=buffer,
                    file_name="hamori_mixed.wav",
                    mime="audio/wav"
                )
                                
                buffer = io.BytesIO()
                sf.write(buffer, y_hamori[:len_min], sr, format='WAV')
                buffer.seek(0)

                st.audio(buffer, format='audio/wav')

                st.download_button(
                    label="ハモリのみ音源をダウンロード",
                    data=buffer,
                    file_name="hamori_only.wav",
                    mime="audio/wav"
                )
                
            else:
                st.error("分析に失敗しました。音声が含まれていない可能性があります。")
